# Thông tin CSDL
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/security_jwt_db
jdbc.username=root
jdbc.password=123456

# Hibernate
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true

# ? Th? m?c l?u ?nh upload (nên là th? m?c tuy?t ??i)
upload.image.dir=/mnt/projects/BE/base_JWT/src/main/resources/static/img/
